class Board_Info:
    pin_num: int
    JTAG_TCK: int
    JTAG_TDI: int
    JTAG_TMS: int
    JTAG_TDO: int
    ISP_RX: int
    ISP_TX: int
    WIFI_TX: int
    WIFI_RX: int
    WIFI_EN: int
    PIN9: int
    PIN10: int
    PIN11: int
    LED_B: int
    LED_G: int
    LED_R: int
    PIN15: int
    BOOT_KEY: int
    PIN17: int
    MIC_ARRAY_BCK: int
    MIC_ARRAY_WS: int
    MIC_ARRAY_DATA3: int
    MIC_ARRAY_DATA2: int
    MIC_ARRAY_DATA1: int
    MIC_ARRAY_DATA0: int
    MIC_ARRAY_LED: int
    SPI0_CS1: int
    SPI0_MISO: int
    SPI0_CLK: int
    SPI0_MOSI: int
    SPI0_CS0: int
    MIC0_WS: int
    MIC0_DATA: int
    MIC0_BCK: int
    I2S_WS: int
    I2S_DA: int
    I2S_BCK: int
    LCD_CS: int
    LCD_RST: int
    LCD_DC: int
    LCD_WR: int
    DVP_SDA: int
    DVP_SCL: int
    DVP_RST: int
    DVP_VSYNC: int
    DVP_PWDN: int
    DVP_HSYNC: int
    DVP_XCLK: int
    DVP_PCLK: int
